name: sbuglider
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyh0d26453_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.14.0=h3fc5862_101_cp314
  - python_abi=3.14=1_cp314
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - bitarray==3.8.0
      - bitstring==4.3.1
      - certifi==2025.10.5
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - dask==2025.10.0
      - fsspec==2025.10.0
      - gsw==3.6.20
      - idna==3.11
      - locket==1.0.0
      - netcdf4==1.7.3
      - numpy==2.3.4
      - packaging==25.0
      - pandas==2.3.3
      - partd==1.4.2
      - platformdirs==4.5.0
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - pooch==1.8.2
      - pyglider==0.0.7
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.16.3
      - six==1.17.0
      - toolz==1.1.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xarray==2025.10.1
prefix: /home/gsb/miniconda3/envs/sbuglider
