metadata:
  cdm_data_type: Trajectory
  conventions: "CF-1.6, COARDS, ACDD-1.3"
  creator_email: gliderdata@marine.rutgers.edu
  creator_name: Matthew Learn
  creator_type: person
  creator_institution: Stony Brook University
  creator_url: http://po.somas.stonybrook.edu/OGP
  featureType: Trajectory
  format_version: IOOS_Glider_NetCDF_v2.0.nc
  geospatial_bounds_crs: "EPSG:4326"
  geospatial_bounds_vertical_crs: "EPSG:5831"
  geospatial_lat_resolution: 0.00001 degree
  geospatial_lat_units: degree_north
  geospatial_lon_resolution: 0.00001 degree
  geospatial_lon_units: degree_east
  geospatial_vertical_positive: down
  geospatial_vertical_units: "EPSG:5831"
  instrument: In Situ/Laboratory Instruments > Profilers/Sounders > CTD
  keywords: "AUVS, Autonomous Underwater Vehicles, Oceans, Ocean Pressure,
             Water Pressure, Oceans, Ocean Temperature, Water Temperature,
             Oceans, Salinity/Density, Conductivity, Oceans,
             Salinity/Density, Density, Oceans, Salinity/Density, Salinity"
  keywords_vocabulary: NASA/GCMD Earth Sciences Keywords Version 8.5
  license: "This data may be redistributed and used without restriction or
            warranty. Data provided as is with no expressed or implied assurance of quality assurance or quality control."
  Metadata_Conventions: CF-1.8, Unidata Dataset Discovery v1.0
  naming_authority: "edu.rutgers.rucool"
  ncei_template_version: NCEI_NetCDF_Trajectory_Template_v2.0
  platform: "In Situ Ocean-based Platforms > AUVS > Autonomous Underwater Vehicles"
  platform_type:    "Slocum Glider"
  processing_level: "Raw Slocum glider time-series dataset from the native data file format. No quality control provided."
  publisher_email: matthew.learn@stonybrook.edu
  publisher_institution: Stony Brook University
  publisher_name:  Matthew Learn
  publisher_url:   https://www.stonybrook.edu/somas/
  source:     Observational data from a profiling glider.
  standard_name_vocabulary: CF Standard Name Table v27


instruments:

platform:


# map between glider variables and netcdf variables.  This shouldn't
# change too much.
netcdf_variables:
  # Time and Place:
  time:
    source:   sci_m_present_time
    long_name:     Time
    standard_name: time
    calendar:      gregorian
    units:         seconds since 1970-01-01T00:00:00Z
    axis:          T
    observation_type: "measured"

  latitude:
    source:  m_lat
    long_name:    latitude
    standard_name: latitude
    units:        degrees_north
    axis:         Y
    comment:     "Estimated between surface fixes"
    observation_type: measured
    platform:     platform
    reference:    WGS84
    valid_max:    90.0
    valid_min:    -90.0
    coordinate_reference_frame:  urn:ogc:crs:EPSG::4326

  longitude:
    source:  m_lon
    long_name:    longitude
    standard_name: longitude
    units:        degrees_east
    axis:         X
    comment:     "Estimated between surface fixes"
    observation_type: measured
    platform:     platform
    reference:    WGS84
    valid_max:    180.0
    valid_min:    -180.0
    coordinate_reference_frame:  urn:ogc:crs:EPSG::4326

  heading:
    source:  m_heading
    long_name:    glider heading angle
    standard_name: platform_orientation
    units:        degrees

  pitch:
    source:  m_pitch
    long_name:    glider pitch angle
    standard_name: platform_pitch_angle
    units:        degrees

  roll:
    source:  m_roll
    long_name:    glider roll angle
    standard_name: platform_roll_angle
    units:        degrees

  # profile info:
  waypoint_latitude:
    source:  c_wpt_lat
    long_name:    waypoint latitude
    standard_name: latitude
    units:        degree_north

  waypoint_longitude:
    source:  c_wpt_lon
    long_name:    waypoint longitude
    standard_name: longitude
    units:        degree_east

  # data parameters
  conductivity:
    source:  sci_water_cond
    long_name:    water conductivity
    standard_name: sea_water_electrical_conductivity
    units:        S m-1
    instrument:    instrument_ctd
    valid_min:    0.
    valid_max:    10.
    observation_type: "measured"
    accuracy:      0.0003
    precision:     0.0001
    resolution:     0.00002

  temperature:
    source:  sci_water_temp
    long_name:    water temperature
    standard_name: sea_water_temperature
    units:        Celsius
    instrument:   instrument_ctd
    valid_min:    -5.0
    valid_max:    50.0
    observation_type: "measured"
    accuracy:      0.002
    precision:     0.001
    resolution:    0.0002

  pressure:
    source:  sci_water_pressure
    long_name:    water pressure
    standard_name:  sea_water_pressure
    units:        dbar
    conversion:   bar2dbar
    valid_min:    0.0
    valid_max:    2000.0
    positive:      "down"
    reference_datum:  "sea-surface"
    instrument:     "instrument_ctd"
    observation_type: "measured"
    accuracy:         1.0
    precision:        2.0
    resolution:       0.02
    comment:          "ctd pressure sensor"

  m_depth:
    source:  m_depth
    long_name:    Depth
    standard_name:  depth
    units:        m
    valid_min:    0.0
    valid_max:    2000.0
    positive:      "down"
    reference_datum:  "sea-surface"
    Comment: "Depth measured by the glider pressure transducer"

# derived water speed:
  water_velocity_eastward:
    source:    m_final_water_vx
    long_name:      mean eastward water velocity in segment
    standard_name:  barotropic_eastward_sea_water_velocity
    units:          m s-1
    coordinates:   time depth latitude longitude
  
  water_velocity_northward:
    source:    m_final_water_vy
    long_name:      mean northward water velocity in segment
    standard_name:  barotropic_northward_sea_water_velocity
    units:          m s-1
    coordinates:   time depth latitude longitude

profile_variables:
  profile_lat:
    comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
    long_name:         Profile Center Latitude
    observation_type:  calculated
    platform:          platform
    standard_name:     latitude
    units:             degrees_north
    valid_max:         90.0
    valid_min:         -90.0
    source:            latitude

  profile_lon:
    comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
    long_name:         Profile Center Longitude
    observation_type:  calculated
    platform:          platform
    standard_name:     longitude
    units:             degrees_east
    valid_max:         180.0
    valid_min:         -180.0
    source:            longitude

  u:
    comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
    long_name:         Depth-Averaged Eastward Sea Water Velocity
    observation_type:  calculated
    platform:          platform
    standard_name:     eastward_sea_water_velocity
    units:             m s-1
    valid_max:         10.0
    valid_min:         -10.0

  v:
    comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
    long_name:         Depth-Averaged Northward Sea Water Velocity
    observation_type:  calculated
    platform:          platform
    standard_name:     northward_sea_water_velocity
    units:             m s-1
    valid_max:         10.0
    valid_min:         -10.0